version: '3.8'
services:
  redis:
    image: redis:7.2.1
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
